import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const action=async name=>page.locator(`[data-action="${name}"]`).first().click();
const nav=async route=>page.locator(`nav a[href="#${route}"]`).click();
const make=async(prompt,type='auto')=>{await nav('home');await page.locator('#outcome').fill(prompt);await page.locator('#app-type').selectOption(type);await page.locator('#new-project button[type="submit"]').click();await page.locator('#plan-form button[type="submit"]').click();await action('build-start');await page.locator('.sample-app').waitFor();};
try{
 await page.goto('http://localhost:4173');await make('Qualify sales leads and prepare outreach');assert.equal(await page.locator('.kanban-column').count(),3);assert.match(await page.locator('.sample-app').innerText(),/Northstar/);assert.doesNotMatch(await page.locator('.sample-app').innerText(),/Quality triage|material certificate/i);await page.screenshot({path:'verification/07-sales-board.png',fullPage:true});
 await make('Research topics and write sourced briefs');assert.equal(await page.locator('.brief-card').count(),3);await page.screenshot({path:'verification/08-research-briefs.png',fullPage:true});
 await make('Manage my astronomy observations');await page.getByText('Your application is ready for its first item').waitFor();
 await nav('structure');for(const [id,value] of Object.entries({headline:'Observation log',entity:'observation',plural:'observations',fields:'Object, Telescope',stages:'Planned, Observed, Reviewed'}))await page.locator('#'+id).fill(value);await page.locator('#layout').selectOption('board');await page.locator('#structure-form button').click();
 await nav('agents');await action('add-agent');for(const [id,value] of Object.entries({'agent-name':'Evidence reviewer','agent-role':'Check observation notes','agent-input':'Observation','agent-output':'Review note','agent-detail-instructions':'Flag missing source details.'}))await page.locator('#'+id).fill(value);await page.locator('#agent-detail-form button').click();await page.getByRole('heading',{name:'Evidence reviewer',exact:true}).waitFor();
 await nav('build');await action('add-record');await page.locator('#record-title').fill('Jupiter transit');await page.locator('#record-description').fill('Observation prepared for reviewer.');await page.locator('#field0').fill('Jupiter');await page.locator('#field1').fill('100 mm');await page.locator('#record-form button').click();await page.getByText('Jupiter transit',{exact:true}).click();await page.locator('#record-stage-form select').selectOption('Observed');await page.locator('#record-stage-form button').click();assert.match(await page.locator('.kanban-column').nth(1).innerText(),/Jupiter transit/);
 await page.reload();await page.locator('.kanban').waitFor();assert.match(await page.locator('.sample-app').innerText(),/Observation log/);await page.screenshot({path:'verification/09-custom-application.png',fullPage:true});
 await page.locator('[data-action="mode"][data-value="technical"]').click();await page.locator('[data-action="work-tab"][data-value="code"]').click();await page.locator('[data-action="file"][data-value="app.schema.json"]').click();assert.match(await page.locator('.code-workspace').innerText(),/observation/);
 await page.setViewportSize({width:390,height:844});const overflow=[];for(const route of ['home','templates','structure','agents','build']){await nav(route);const g=await page.evaluate(()=>({w:document.documentElement.clientWidth,s:document.documentElement.scrollWidth}));if(g.s>g.w+1)overflow.push({route,...g});}
 await nav('home');await page.locator('#new-project').waitFor();assert.equal(await page.locator('.project-card').count(),3);await page.screenshot({path:'verification/10-platform-mobile.png',fullPage:true});
 const result={date:new Date().toISOString(),browser:'Isolated local Chrome',verified:['Sales prompt creates sales agents/data and board','Research prompt creates briefs and distinct records','Unmatched prompt starts a blank custom app','Custom labels, fields, stages and layout affect preview','Add agent and inspect exported contracts','Add record with custom values and move stage','Reload preserves custom app','Multiple independent projects','Mobile route overflow'],pageErrors:errors,horizontalOverflow:overflow};await fs.writeFile('verification/platform-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));assert.deepEqual(errors,[]);assert.deepEqual(overflow,[]);
}finally{await browser.close();}

