import test from 'node:test';
import assert from 'node:assert/strict';
import {createProject,transition,readiness,inspectImport,sampleImport,fileMap,initialState,restoreState} from '../dist/state.js';
const act=(p,type,data)=>transition(p,{type,data});
function ready(){let p=createProject();p=act(p,'PLAN',{outcome:p.outcome,owner:p.owner,threshold:p.threshold});p=act(p,'BUILD_START');p=act(p,'BUILD_DONE');p=act(p,'CONNECTION',{key:'knowledge',status:'connected'});return act(p,'TEST',{kind:'suite'});}
test('business journey: plan, build, impact, permission recovery, release retry and rollback',()=>{
 let p=ready();const original=structuredClone(p);p=act(p,'PROPOSE',{text:'Add Teams alerts'});assert.equal(p.notifications,false);assert.equal(p.pending.impact.length,3);p=act(p,'APPLY');assert.equal(p.notifications,true);assert(p.tools.includes('teams.notify'));assert.equal(p.tests.length,0);assert.throws(()=>act(p,'DEPLOY_START'),/release checks/);
 p=act(p,'CONNECTION',{key:'teams',status:'denied'});p=act(p,'TEST',{kind:'suite'});assert.equal(p.tests[0].passed,false);p=act(p,'CONNECTION',{key:'teams',status:'connected'});p=act(p,'TEST',{kind:'suite'});p=act(p,'DEPLOY_START');p=act(p,'DEPLOY_FAIL');assert.equal(p.releases.length,0);p=act(p,'DEPLOY_START');p=act(p,'DEPLOY_DONE');const first=p.activeRelease;
 p=act(p,'PROPOSE',{text:'Set response to 12 hours'});p=act(p,'APPLY');assert.equal(JSON.parse(fileMap(p)['app.config.json']).responseHours,12);p=act(p,'TEST',{kind:'suite'});p=act(p,'DEPLOY_START');p=act(p,'DEPLOY_DONE');assert.equal(p.releases.length,2);p=act(p,'ROLLBACK',{id:first});assert.equal(p.sla,24);assert.equal(p.activeRelease,first);assert.equal(p.tests.length,0);assert.equal(original.notifications,false);
});
test('developer journey: manifest validation, configuration, conflict and sync',()=>{
 assert.throws(()=>inspectImport('{'),/valid JSON/);assert.throws(()=>inspectImport(JSON.stringify({...sampleImport,framework:'MadeUp'})),/contract/);assert.throws(()=>inspectImport(JSON.stringify({...sampleImport,files:['../secrets']})),/safe/);
 const m=inspectImport(JSON.stringify(sampleImport));let p=createProject(m.name,true);assert.equal(p.connections.model,'missing');p=act(p,'TEST',{kind:'suite'});assert.equal(p.tests[0].passed,false);
 for(const key of ['knowledge','model'])p=act(p,'CONNECTION',{key,status:'connected'});p=act(p,'AGENT',{instructions:'Require evidence and qualified review.',framework:'CrewAI',model:'Fast · sample model'});assert.equal(JSON.parse(fileMap(p)['agents/triage.contract.json']).framework,'CrewAI');
 p=act(p,'GITHUB_CONNECT');p=act(p,'GITHUB_CONFLICT');assert.throws(()=>act(p,'GITHUB_SYNC'),/conflicts/);p=act(p,'GITHUB_RESOLVE',{choice:'remote'});assert.equal(p.sla,48);p=act(p,'GITHUB_SYNC');assert.equal(p.github.syncedRevision,p.revision);p=act(p,'TEST',{kind:'suite'});assert(readiness(p).every(c=>c.ok));
});
test('stale proposals cannot overwrite new configuration; undo restores all coupled fields',()=>{let p=ready();p=act(p,'PROPOSE',{text:'Add Teams alerts'});p=act(p,'CONNECTION',{key:'model',status:'connected'});assert.throws(()=>act(p,'APPLY'),/changed after/);p=act(p,'PROPOSE',{text:'Add Teams alerts'});p=act(p,'APPLY');p=act(p,'UNDO');assert.equal(p.notifications,false);assert(!p.tools.includes('teams.notify'));assert.equal(p.tests.length,0);});
test('release rejects changes made while deploying',()=>{let p=ready();p=act(p,'DEPLOY_START');p=act(p,'CONNECTION',{key:'knowledge',status:'missing'});p=act(p,'DEPLOY_DONE');assert.equal(p.releaseStatus,'failed');assert.equal(p.releases.length,0);});
test('test failures, numeric boundaries, unknown edits, cancellation and rehydration',()=>{let p=createProject();assert.throws(()=>act(p,'BUILD_START'),/Approve/);assert.throws(()=>act(p,'PROPOSE',{text:'threshold 100'}),/50 to 99/);assert.throws(()=>act(p,'PROPOSE',{text:'do anything'}),/supports/);p=ready();p=act(p,'TEST',{kind:'timeout'});assert.equal(p.tests[0].passed,false);p=act(p,'BUILD_START');p=act(p,'BUILD_CANCEL');assert.equal(p.stage,'cancelled');p=act(p,'BUILD_START');const state={...initialState(),active:p.id,projects:[p]};assert.equal(restoreState(JSON.stringify(state)).projects[0].stage,'cancelled');assert.deepEqual(restoreState('{'),initialState());assert.deepEqual(restoreState('{"schema":1,"projects":[{}]}'),initialState());});
test('changes are immutable, automatic sync stops on conflict, and release snapshots are independent',()=>{let p=ready();const old=structuredClone(p);p=act(p,'GITHUB_CONNECT');p=act(p,'GITHUB_SYNC');p=act(p,'SETTINGS',{name:'New name',budget:50});assert.equal(p.github.syncedRevision,p.revision);p=act(p,'GITHUB_CONFLICT');p=act(p,'SETTINGS',{name:'Another name',budget:50});assert.notEqual(p.github.syncedRevision,p.revision);assert.equal(old.name,'Sitewise · Quality triage');});
